### ISSUE TITLE
Checklist of things to implement (in order)

### ISSUE THREAD

**Issue by konradsic** [konradsic/dj-cloudy#39]
# The checklist
This checklist is updated regularly (if something changes or if something is done). It is a kind of a "roadmap" for the bot and it represents a list of things that need to be done in order to release a version (versions are also marked in this checklist).
> [!NOTE]
> If a checklist point is an issue it means that that point is completed when the issue is resolved and closed

- [x] #45 
- [x] #37
- [x] #47 
- [x] #31 
- [x] #44 
- [x] #38 
- [x] #46 
- [x] Could do #25
- [x] #30 
- [x] #33 
- [x] #50
- [x] #43 
- [x] un-private the bot and prepare everything for that
- [x] Release 1.4.0-stable
- [x] #22 
- [x] #24 (should be easy)
- [x] #52 
- [x] #48 
- [x] #18 
- [x] #49 
- [x] #23 
- [x] Release 1.5.0 (after bug fixes)
- [ ] #35 (finish all bullet points from that issue)
- [x] #32 
- [ ] Bug fixes
- [ ] Release 1.6.0
- [x] #42 
- [ ] Redesign emojis and the whole bot
- [ ] Release 2.0 [!!!]

**Comment by konradsic** [comment]
im lazy af
